apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: libra
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=         
  POSTGRES_PASSWORD: Z292aW5kQDEyMw==  
  POSTGRES_DB: bGlicmFfZGI=       